### ISSUE TITLE
Add support to Grommet for styled-components v6.0.0

### ISSUE THREAD

**Issue by jim-king-2000** [grommet/grommet#6857]
Grommet can't work with styled-components@6.0.0.

### Expected Behavior

Works as if it were styled-components@5.x.x.

### Actual Behavior

Error message:
```console
TypeError: defaultValidatorFn is not a function
```

### URL, screen shot, or Codepen exhibiting the issue

None

### Steps to Reproduce

1. Clone the code here: <https://github.com/jim-king-2000/testGrommet>
1. `npm i&&npm run dev`
1. Browse `localhost:3000` and see the result.

### Your Environment

- Grommet version: 2.32.2
- Browser Name and version: Chrome v114
- Operating System and version (desktop or mobile): Win11

**Comment by lindsaylevine** [comment]
➕

**Comment by jcfilben** [comment]
Hey just wanted to give an update that this issue is on our radar and we are hoping to get support out for styled-components v6 soon

**Comment by jim-king-2000** [comment]
Fixed.

**Comment by jim-king-2000** [comment]
any update?

**Comment by kwihpe** [comment]
**+**

**Comment by jcfilben** [comment]
We are still actively working on this, it touches a ton of areas in Grommet so we are being careful to ensure we do this correctly in a backwards compatible way.

**Comment by jim-king-2000** [comment]
Any update?

**Comment by jcfilben** [comment]
Hi @jim-king-2000 the team is currently exploring some different approaches we could take to upgrade styled components. We are hoping to get a beta release out soon, but we don't have a solid timeline yet. Still working through a few issues, but we know this upgrade is important and we are working to get it out there.

**Comment by jim-king-2000** [comment]
Looking forward to the upgrade and good luck.

**Comment by britt6612** [comment]
@jim-king-2000 @kwihpe @lindsaylevine 
we are happy to announce we just shipped a pre-release that adds support for `styled components v6`.

[here](https://github.com/grommet/grommet/releases/tag/v2.35.0-alpha.1) you can find the pre-release notes. Let us know if you have any questions or feedback as always 😄

**Comment by jim-king-2000** [comment]
Fantastic! Can't wait more time.

**Comment by jim-king-2000** [comment]
It works! Looking forward to the production release.
