### ISSUE TITLE
New style Box HOCs cause hard error with ParcelJS

### ISSUE THREAD

**Issue by erikreedstrom** [grommet/grommet#2618]
### Expected Behavior

Able to use ParcelJS to bundle applications using Grommet >= v2.1.1

### Actual Behavior

When using ParcelJS as a bundler, Grommet v2.1.1 fails with an error.

### URL, screen shot, or Codepen exhibiting the issue

```js
Uncaught Error: Cannot find module './Box/doc'
    at newRequire (src.7ed060e2.js:39)
    at localRequire (src.7ed060e2.js:55)
    at doc (hocs.js:27)
    at Object.parcelRequire.../node_modules/grommet/es6/components/Box/Box.js.react (Box.js:20)
    at newRequire (src.7ed060e2.js:49)
    at localRequire (src.7ed060e2.js:55)
    at Object.parcelRequire.../node_modules/grommet/es6/components/Box/index.js../Box (index.js:1)
    at newRequire (src.7ed060e2.js:49)
    at localRequire (src.7ed060e2.js:55)
    at Object.parcelRequire.../node_modules/grommet/es6/components/Accordion/Accordion.js.react (Accordion.js:12)
```

### Steps to Reproduce

1. Use ParcelJS as bundler
2. Include `Box` as a dependency
3. Run server and attempt to access

Have verified this does not happen in v2.1.0. It seems it was likely introduced here:
https://github.com/grommet/grommet/commit/4c7c0522f247f4b395732c36a1a614c94dc08f4d

### Your Environment

- Grommet version: 2.1.1
- Browser Name and version: Chrome 71
- Operating System and version (desktop or mobile): Desktop

**Comment by michaelauderer** [comment]
I'm also experiencing this exact issue on a new project with v2.2.0.

**Comment by ShimiSun** [comment]
have you tried with the Latest release (2.4.0) to see if the issue still exists?

**Comment by cafrias** [comment]
I'm experiencing the same issue with version `2.4.0`, I got it working with version `2.1.0`. My version of `parcel-bundler` is `1.11.0`

**Comment by shabtaisharon** [comment]
I believe this issue does not lie inside of Grommet, since all of my other applications that use webpack, react app or nodejs does not have this issue.

My suggestion is to use `cross-env` to set `NODE_ENV=production` when you run your server.
1. Install `cross-env` -> `npm install --save-dev cross-env`
2. Update your `start` script in `package.json` -> `"start": "cross-env NODE_ENV=production parcel index.html"`

This should solve your issue, i'm currently using grommet `v2.5.5`

**Comment by oorestisime** [comment]
@erikreedstrom does this work for you? can we close this?

**Comment by ShimiSun** [comment]
@michaelauderer, @cafrias, @miguelpeixe, @one19, @hlynn93 is the set up offered by @shabtaisharon helped you to overcome the problem?

**Comment by one19** [comment]
that leaves a bit to be desired, honestly.

Forcing the bundling tool for an entire application to run in production mode _(much slower, and without many benefits)_ because of a very strangely pathed documentation HOC import in a single dependency seems like the cart leading the horse.

My use case is better served by not upgrading grommet until a better solution is found.

**Comment by sbilstein** [comment]
Agree. Pegging my bundler to production introduces issues with other packages. Will downgrade grommet for now.

**Comment by midnightcodr** [comment]
Forcing a project to run in production environment should not be the ideal solution. I just discovered grommet recently and being not able to work with parcel bundler (without using production mode) is really a shame. I am hoping this issue is fixed soon so I can give it another try.

**Comment by oorestisime** [comment]
Hello thanks all for the feedback. Agreed current situation is not ideal. I will try and come up with a solution in the next days!

**Comment by ShimiSun** [comment]
Thank you all for the collaboration and feedback. we reverted the changes that caused the issue, and Grommet & ParcelJS should work as expected on `https://github.com/grommet/grommet/tarball/stable`.
I'll do an official release in the next couple of days that will include the fix.

**Comment by shabtaisharon** [comment]
Thanks, @ShimiSun & @oorestisime that fixed my issue and I no longer need to set the `production` flag.
